export const ApiRoutes = {
  CREATE_USER: "/v1/users",
  LIST_USERS: "/v1/users",
  UPDATE_USER: "/v1/users",
  CHANGE_ADMIN: "/v1/users/change-admin",
  LOGIN_USER: "/v1/auth/login",
  USER_ME: "/v1/users/me",
  LIST_BUS: "/v1/bus",
  FILTER_BUS: "/v1/bus/line",
  CREATE_BUS: "/v1/bus",
  SEARCH_BUS: "/v1/bus",
  LOGOUT: "/v1/auth/logout",
  LIST_BUS_USER: "/v1/bus/user",
  FAVORITE_BUS: "/v1/users/favorite-bus",
  DISFAVOR_BUS: "/v1/users/desfavorite-bus",
  LIST_GROUP_PERMISSIONS: "/v1/permissions",
  LOGS: "/v1/logs",
  GET_BUS_STATISTICS: '/v1/bus/statistics',
};
